# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir G:/junior/CPU/final_cpu/final_cpu.cache/wt [current_project]
set_property parent.project_path G:/junior/CPU/final_cpu/final_cpu.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo g:/junior/CPU/final_cpu/final_cpu.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  G:/junior/CPU/final_cpu/final_cpu.srcs/sources_1/imports/CPU_mxh/ALU.v
  G:/junior/CPU/final_cpu/final_cpu.srcs/sources_1/imports/CPU_mxh/IM.v
  G:/junior/CPU/final_cpu/final_cpu.srcs/sources_1/imports/CPU_mxh/RAM.v
  G:/junior/CPU/final_cpu/final_cpu.srcs/sources_1/imports/CPU_mxh/RegFile.v
  G:/junior/CPU/final_cpu/final_cpu.srcs/sources_1/imports/CPU_mxh/controller.v
  G:/junior/CPU/final_cpu/final_cpu.srcs/sources_1/imports/CPU_mxh/counter.v
  G:/junior/CPU/final_cpu/final_cpu.srcs/sources_1/imports/CPU_mxh/data_extend.v
  G:/junior/CPU/final_cpu/final_cpu.srcs/sources_1/new/divider.v
  G:/junior/CPU/final_cpu/final_cpu.srcs/sources_1/imports/CPU_mxh/hex_to_dec.v
  G:/junior/CPU/final_cpu/final_cpu.srcs/sources_1/imports/CPU_mxh/mux.v
  G:/junior/CPU/final_cpu/final_cpu.srcs/sources_1/imports/CPU_mxh/mux_4_5.v
  G:/junior/CPU/final_cpu/final_cpu.srcs/sources_1/imports/CPU_mxh/npc.v
  G:/junior/CPU/final_cpu/final_cpu.srcs/sources_1/imports/CPU_mxh/pattern.v
  G:/junior/CPU/final_cpu/final_cpu.srcs/sources_1/imports/CPU_mxh/pc.v
  G:/junior/CPU/final_cpu/final_cpu.srcs/sources_1/imports/CPU_mxh/pcenable.v
  G:/junior/CPU/final_cpu/final_cpu.srcs/sources_1/imports/CPU_mxh/syscall.v
  G:/junior/CPU/final_cpu/final_cpu.srcs/sources_1/imports/CPU_mxh/CPU.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc G:/junior/CPU/final_cpu/final_cpu.srcs/constrs_1/imports/CPU/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files G:/junior/CPU/final_cpu/final_cpu.srcs/constrs_1/imports/CPU/Nexys4DDR_Master.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top CPU -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef CPU.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file CPU_utilization_synth.rpt -pb CPU_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
